language: go
sudo: false
go:
  - 1.9
cache:
  directories:
    - vendor
install:
  - make dep
script:
  - make
after_success:
  - travis_retry make coveralls
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
